export interface PokemonTypeConstants {
    grass: string,
    fire: string,
    water: string,
    poison: string,
    flying: string,
    electric: string,
    bug: string,
    ice: string,
    rock: string,
    ground: string,
    steel: string,
    dragon: string,
    psychic: string,
    ghost: string,
    dark: string,
    normal: string,
    fighting: string,
}